### ISSUE TITLE
Show fullcalendar when resources are selected

### ISSUE THREAD

**Issue by davisg123** [ECE-458-Resource-Manager/ResourceManager#5]

**Comment by sam-ginsburg** [comment]
I didn't think we wanted fullcalendar on the main page, we want fullcalendar to show up when a user selects a resource, right?

**Comment by davisg123** [comment]
Yea, so this will only show when resources are selected

**Comment by davisg123** [comment]
Set fullcalendar options and added hooks: 789704039ca9c7ae06ea7bb647fd042458f67d92
